### ISSUE TITLE
Feature request: Hacker theme with colorful keywords

### ISSUE THREAD

**Issue by hm72747** [thorerik/vscode-hacker-theme#1]
I really like this theme. I think it would be cool if it had a color variation where keywords are marked in different colors in the code but mantaining the hacker spirit. 

![Clipboard01](https://user-images.githubusercontent.com/69722291/90334989-8dcc6c00-df9f-11ea-9187-fe08b8bc6021.jpg)

![Clipboard02](https://user-images.githubusercontent.com/69722291/90334991-91f88980-df9f-11ea-98d6-cc073ebe0528.jpg)

**Comment by somarlyonks** [comment]
Objection! Cheesy colors like that will kill the spirit definitely.

**Comment by hm72747** [comment]
Good work!
